name: Rust Book Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build enums
      run: cd ${{github.workspace}}/enums; cargo build --verbose
    - name: build functions
      run: cd ${{github.workspace}}/functions; cargo build --verbose
    - name: build guessing_game
      run: cd ${{github.workspace}}/guessing_game ; cargo build --verbose
    - name: build hello_cargo
      run: cd ${{github.workspace}}/hello_cargo; cargo build --verbose
    - name: build ownership
      run: cd ${{github.workspace}}/ownership; cargo build --verbose
    - name: build rectangles
      run: cd ${{github.workspace}}/rectangles; cargo build --verbose
    - name: build structs
      run: cd ${{github.workspace}}/structs; cargo build --verbose
    - name: build variables
      run: cd ${{github.workspace}}/variables; cargo build --verbose
    - name: build ToyWebServer
      run: cd ${{github.workspace}}/toy_web_server; cargo build --verbose
